// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFE1bRCGP00qR4Tpzw7bAye0KODQijQqY',
    appId: '1:366823917336:web:a4ebf73d3f314d5231006d',
    messagingSenderId: '366823917336',
    projectId: 'chatappflutter-95ee4',
    authDomain: 'chatappflutter-95ee4.firebaseapp.com',
    storageBucket: 'chatappflutter-95ee4.appspot.com',
    measurementId: 'G-ZQWC5NS76Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFg-evWyVECISn_H-XqLqxGi--FPw4U4Y',
    appId: '1:366823917336:android:dbcc809864855a7531006d',
    messagingSenderId: '366823917336',
    projectId: 'chatappflutter-95ee4',
    storageBucket: 'chatappflutter-95ee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQqemZgEcS-ceZMElZh294MefkEElx-Y',
    appId: '1:366823917336:ios:ff3b1c46e1be6efa31006d',
    messagingSenderId: '366823917336',
    projectId: 'chatappflutter-95ee4',
    storageBucket: 'chatappflutter-95ee4.appspot.com',
    iosBundleId: 'com.example.groupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQqemZgEcS-ceZMElZh294MefkEElx-Y',
    appId: '1:366823917336:ios:ff3b1c46e1be6efa31006d',
    messagingSenderId: '366823917336',
    projectId: 'chatappflutter-95ee4',
    storageBucket: 'chatappflutter-95ee4.appspot.com',
    iosBundleId: 'com.example.groupchat',
  );
}
